import 'package:equatable/equatable.dart';

/// Represents a single flashcard generated by AI.
class FlashcardModel extends Equatable {
  final String id;
  final String question;
  final String answer;
  final String? topic;

  const FlashcardModel({
    required this.id,
    required this.question,
    required this.answer,
    this.topic,
  });

  factory FlashcardModel.fromJson(Map<String, dynamic> json) {
    return FlashcardModel(
      id: json['id'] as String? ?? DateTime.now().millisecondsSinceEpoch.toString(),
      question: json['question'] as String,
      answer: json['answer'] as String,
      topic: json['topic'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'question': question,
        'answer': answer,
        'topic': topic,
      };

  @override
  List<Object?> get props => [id, question, answer, topic];
}
